/*
 * generated by Xtext 2.9.2
 */
package io.chark.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class Kebab_LangIdeaModule extends AbstractKebab_LangIdeaModule {
}
