/*
 * generated by Xtext 2.9.2
 */
package io.chark.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class Kebab_LangIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new Kebab_LangStandaloneSetupIdea().createInjector
	}

}
