/*
 * generated by Xtext 2.9.2
 */
package io.chark


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Kebab_LangStandaloneSetup extends Kebab_LangStandaloneSetupGenerated {

	def static void doSetup() {
		new Kebab_LangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
