/*
 * generated by Xtext 2.9.2
 */
package io.chark


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class Kebab_LangRuntimeModule extends AbstractKebab_LangRuntimeModule {
}
