/**
 * generated by Xtext 2.9.2
 */
package io.chark.scoping;

import io.chark.scoping.AbstractKebab_LangScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class Kebab_LangScopeProvider extends AbstractKebab_LangScopeProvider {
}
