/**
 * generated by Xtext 2.9.2
 */
package io.chark.idea.completion;

import io.chark.idea.completion.AbstractKebab_LangCompletionContributor;
import io.chark.idea.lang.Kebab_LangLanguage;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

@SuppressWarnings("all")
public class Kebab_LangCompletionContributor extends AbstractKebab_LangCompletionContributor {
  public Kebab_LangCompletionContributor() {
    this(Kebab_LangLanguage.INSTANCE);
  }
  
  public Kebab_LangCompletionContributor(final AbstractXtextLanguage lang) {
    super(lang);
  }
}
