/**
 * generated by Xtext 2.9.2
 */
package io.chark.idea;

import io.chark.idea.AbstractKebab_LangIdeaModule;

/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
@SuppressWarnings("all")
public class Kebab_LangIdeaModule extends AbstractKebab_LangIdeaModule {
}
