/**
 * generated by Xtext 2.9.2
 */
package io.chark.idea;

import com.google.inject.Injector;
import io.chark.idea.Kebab_LangStandaloneSetupIdea;
import org.eclipse.xtext.ISetup;
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries;

@SuppressWarnings("all")
public class Kebab_LangIdeaSetup implements ISetup {
  @Override
  public Injector createInjectorAndDoEMFRegistration() {
    Injector _xblockexpression = null;
    {
      EcoreGlobalRegistries.ensureInitialized();
      Kebab_LangStandaloneSetupIdea _kebab_LangStandaloneSetupIdea = new Kebab_LangStandaloneSetupIdea();
      _xblockexpression = _kebab_LangStandaloneSetupIdea.createInjector();
    }
    return _xblockexpression;
  }
}
