/**
 * generated by Xtext 2.9.2
 */
package io.chark.idea;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import io.chark.Kebab_LangRuntimeModule;
import io.chark.Kebab_LangStandaloneSetupGenerated;
import io.chark.idea.Kebab_LangIdeaModule;
import org.eclipse.xtext.util.Modules2;

@SuppressWarnings("all")
public class Kebab_LangStandaloneSetupIdea extends Kebab_LangStandaloneSetupGenerated {
  @Override
  public Injector createInjector() {
    final Kebab_LangRuntimeModule runtimeModule = new Kebab_LangRuntimeModule();
    final Kebab_LangIdeaModule ideaModule = new Kebab_LangIdeaModule();
    final Module mergedModule = Modules2.mixin(runtimeModule, ideaModule);
    return Guice.createInjector(mergedModule);
  }
}
