/*
 * generated by Xtext 2.9.2
 */
package io.chark.idea.highlighting;

import io.chark.idea.lang.Kebab_LangLanguage;
import org.eclipse.xtext.idea.highlighting.AbstractColorSettingsPage;

public class Kebab_LangBaseColorSettingsPage extends AbstractColorSettingsPage {
	
	public Kebab_LangBaseColorSettingsPage() {
		Kebab_LangLanguage.INSTANCE.injectMembers(this);
	}

	@Override
	public String getDisplayName() {
		return Kebab_LangLanguage.INSTANCE.getDisplayName();
	}
}
