/*
 * generated by Xtext 2.9.2
 */
package io.chark.idea.highlighting;

import io.chark.idea.lang.Kebab_LangLanguage;
import org.eclipse.xtext.idea.highlighting.SemanticHighlightVisitor;

public class Kebab_LangSemanticHighlightVisitor extends SemanticHighlightVisitor {
	public Kebab_LangSemanticHighlightVisitor() {
		Kebab_LangLanguage.INSTANCE.injectMembers(this);
	}
}
