/**
 * generated by Xtext 2.9.2
 */
package io.chark.idea.lang;

import io.chark.idea.lang.AbstractKebab_LangFileType;
import io.chark.idea.lang.Kebab_LangLanguage;

@SuppressWarnings("all")
public class Kebab_LangFileType extends AbstractKebab_LangFileType {
  public final static Kebab_LangFileType INSTANCE = new Kebab_LangFileType();
  
  public Kebab_LangFileType() {
    super(Kebab_LangLanguage.INSTANCE);
  }
}
