/*
 * generated by Xtext 2.9.2
 */
package io.chark.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import io.chark.idea.lang.Kebab_LangLanguage;
import org.eclipse.xtext.idea.facet.AbstractFacetType;

public class Kebab_LangFacetType extends AbstractFacetType<Kebab_LangFacetConfiguration> {

	public static final FacetTypeId<Facet<Kebab_LangFacetConfiguration>> TYPEID = new FacetTypeId<Facet<Kebab_LangFacetConfiguration>>("io.chark.Kebab_Lang");

	public Kebab_LangFacetType() {
		super(TYPEID, "io.chark.Kebab_Lang", "Kebab_Lang");
		Kebab_LangLanguage.INSTANCE.injectMembers(this);
	}
}
