/*
 * generated by Xtext 2.9.2
 */
package io.chark.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractKebab_LangScopeProvider extends DelegatingScopeProvider {
}
