/*
 * generated by Xtext 2.9.2
 */
package io.chark.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractKebab_LangCompletionContributor extends TerminalsCompletionContributor {
	public AbstractKebab_LangCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
