/*
 * generated by Xtext 2.9.2
 */
package io.chark.idea.lang


class Kebab_LangFileType extends AbstractKebab_LangFileType {
	public static final Kebab_LangFileType INSTANCE = new Kebab_LangFileType()
	
	new() {
		super(Kebab_LangLanguage.INSTANCE)
	}
}
