/**
 * generated by Xtext 2.9.2
 */
package io.chark.validation;

import io.chark.validation.AbstractKebab_LangValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class Kebab_LangValidator extends AbstractKebab_LangValidator {
}
