/*
 * generated by Xtext 2.9.2
 */
package io.chark.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractKebab_LangValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(io.chark.kebab_Lang.Kebab_LangPackage.eINSTANCE);
		return result;
	}
	
}
