/*
 * generated by Xtext 2.9.2
 */
package io.chark.idea.completion

import io.chark.idea.lang.Kebab_LangLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class Kebab_LangCompletionContributor extends AbstractKebab_LangCompletionContributor {
	new() {
		this(Kebab_LangLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
