/**
 * generated by Xtext 2.9.2
 */
package io.chark;

import io.chark.AbstractKebab_LangRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class Kebab_LangRuntimeModule extends AbstractKebab_LangRuntimeModule {
}
