/**
 * generated by Xtext 2.9.2
 */
package io.chark;

import io.chark.Kebab_LangStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class Kebab_LangStandaloneSetup extends Kebab_LangStandaloneSetupGenerated {
  public static void doSetup() {
    Kebab_LangStandaloneSetup _kebab_LangStandaloneSetup = new Kebab_LangStandaloneSetup();
    _kebab_LangStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
