/*
 * generated by Xtext 2.9.2
 */
package io.chark.parser.antlr;

import com.google.inject.Inject;
import io.chark.parser.antlr.internal.InternalKebab_LangParser;
import io.chark.services.Kebab_LangGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class Kebab_LangParser extends AbstractAntlrParser {

	@Inject
	private Kebab_LangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalKebab_LangParser createParser(XtextTokenStream stream) {
		return new InternalKebab_LangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public Kebab_LangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Kebab_LangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
