/*
 * generated by Xtext 2.9.2
 */
package io.chark.idea.lang.psi;

import com.intellij.psi.util.PsiModificationTracker;
import io.chark.idea.lang.Kebab_LangLanguage;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;

public class Kebab_LangCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public Kebab_LangCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(Kebab_LangLanguage.INSTANCE, psiModificationTracker);
	}

}
