/*
 * generated by Xtext 2.9.2
 */
package io.chark.idea.lang;

import com.intellij.lang.Language;
import com.intellij.openapi.fileTypes.LanguageFileType;
import javax.swing.Icon;
import org.eclipse.xtext.idea.Icons;
import org.jetbrains.annotations.NonNls;

public class AbstractKebab_LangFileType extends LanguageFileType {

	@NonNls 
	public static final String DEFAULT_EXTENSION = "kebab";

	protected AbstractKebab_LangFileType(final Language language) {
		super(language);
	}

	@Override
	public String getDefaultExtension() {
		return DEFAULT_EXTENSION;
	}

	@Override
	public String getDescription() {
		return "Kebab_Lang files";
	}

	@Override
	public Icon getIcon() {
		return Icons.DSL_FILE_TYPE;
	}

	@Override
	public String getName() {
		return "Kebab_Lang";
	}

}
