/*
 * generated by Xtext 2.9.2
 */
package io.chark.idea.lang;

import com.intellij.psi.tree.IFileElementType;
import io.chark.idea.lang.psi.impl.Kebab_LangFileImpl;
import io.chark.services.Kebab_LangGrammarAccess;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.idea.lang.IElementTypeProvider;
import org.eclipse.xtext.psi.stubs.XtextFileElementType;
import org.eclipse.xtext.psi.stubs.XtextFileStub;
import org.eclipse.xtext.psi.tree.IGrammarAwareElementType;

public class Kebab_LangElementTypeProvider implements IElementTypeProvider {

	public static final IFileElementType FILE_TYPE = new XtextFileElementType<XtextFileStub<Kebab_LangFileImpl>>(Kebab_LangLanguage.INSTANCE);

	private static final Map<EObject, IGrammarAwareElementType> GRAMMAR_ELEMENT_TYPE = new HashMap<EObject, IGrammarAwareElementType>();

	private static IGrammarAwareElementType associate(IGrammarAwareElementType grammarAwareElementType) {
		GRAMMAR_ELEMENT_TYPE.put(grammarAwareElementType.getGrammarElement(), grammarAwareElementType);
		return grammarAwareElementType;
	}

	private static final Kebab_LangGrammarAccess GRAMMAR_ACCESS = Kebab_LangLanguage.INSTANCE.getInstance(Kebab_LangGrammarAccess.class);

	private static class ModelFactory {
		public static IGrammarAwareElementType createModelElementType() {
			return new IGrammarAwareElementType("Model_ELEMENT_TYPE", Kebab_LangLanguage.INSTANCE, GRAMMAR_ACCESS.getModelRule());
		}
		public static IGrammarAwareElementType createModel_GreetingsAssignmentElementType() {
			return new IGrammarAwareElementType("Model_GreetingsAssignment_ELEMENT_TYPE", Kebab_LangLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getGreetingsAssignment());
		}
		public static IGrammarAwareElementType createModel_GreetingsGreetingParserRuleCall_0ElementType() {
			return new IGrammarAwareElementType("Model_GreetingsGreetingParserRuleCall_0_ELEMENT_TYPE", Kebab_LangLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getGreetingsGreetingParserRuleCall_0());
		}
	}

	public static final IGrammarAwareElementType Model_ELEMENT_TYPE = associate(ModelFactory.createModelElementType());

	public static final IGrammarAwareElementType Model_GreetingsAssignment_ELEMENT_TYPE = associate(ModelFactory.createModel_GreetingsAssignmentElementType());

	public static final IGrammarAwareElementType Model_GreetingsGreetingParserRuleCall_0_ELEMENT_TYPE = associate(ModelFactory.createModel_GreetingsGreetingParserRuleCall_0ElementType());

	private static class GreetingFactory {
		public static IGrammarAwareElementType createGreetingElementType() {
			return new IGrammarAwareElementType("Greeting_ELEMENT_TYPE", Kebab_LangLanguage.INSTANCE, GRAMMAR_ACCESS.getGreetingRule());
		}
		public static IGrammarAwareElementType createGreeting_GroupElementType() {
			return new IGrammarAwareElementType("Greeting_Group_ELEMENT_TYPE", Kebab_LangLanguage.INSTANCE, GRAMMAR_ACCESS.getGreetingAccess().getGroup());
		}
		public static IGrammarAwareElementType createGreeting_HelloKeyword_0ElementType() {
			return new IGrammarAwareElementType("Greeting_HelloKeyword_0_ELEMENT_TYPE", Kebab_LangLanguage.INSTANCE, GRAMMAR_ACCESS.getGreetingAccess().getHelloKeyword_0());
		}
		public static IGrammarAwareElementType createGreeting_NameAssignment_1ElementType() {
			return new IGrammarAwareElementType("Greeting_NameAssignment_1_ELEMENT_TYPE", Kebab_LangLanguage.INSTANCE, GRAMMAR_ACCESS.getGreetingAccess().getNameAssignment_1());
		}
		public static IGrammarAwareElementType createGreeting_NameIDTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("Greeting_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE", Kebab_LangLanguage.INSTANCE, GRAMMAR_ACCESS.getGreetingAccess().getNameIDTerminalRuleCall_1_0());
		}
		public static IGrammarAwareElementType createGreeting_ExclamationMarkKeyword_2ElementType() {
			return new IGrammarAwareElementType("Greeting_ExclamationMarkKeyword_2_ELEMENT_TYPE", Kebab_LangLanguage.INSTANCE, GRAMMAR_ACCESS.getGreetingAccess().getExclamationMarkKeyword_2());
		}
	}

	public static final IGrammarAwareElementType Greeting_ELEMENT_TYPE = associate(GreetingFactory.createGreetingElementType());

	public static final IGrammarAwareElementType Greeting_Group_ELEMENT_TYPE = associate(GreetingFactory.createGreeting_GroupElementType());

	public static final IGrammarAwareElementType Greeting_HelloKeyword_0_ELEMENT_TYPE = associate(GreetingFactory.createGreeting_HelloKeyword_0ElementType());

	public static final IGrammarAwareElementType Greeting_NameAssignment_1_ELEMENT_TYPE = associate(GreetingFactory.createGreeting_NameAssignment_1ElementType());

	public static final IGrammarAwareElementType Greeting_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE = associate(GreetingFactory.createGreeting_NameIDTerminalRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType Greeting_ExclamationMarkKeyword_2_ELEMENT_TYPE = associate(GreetingFactory.createGreeting_ExclamationMarkKeyword_2ElementType());

	@Override
	public IFileElementType getFileType() {
		return FILE_TYPE;
	}

	@Override
	public IGrammarAwareElementType findElementType(EObject grammarElement) {
		return GRAMMAR_ELEMENT_TYPE.get(grammarElement);
	}
	
	public IGrammarAwareElementType getModelElementType() {
		return Model_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_GreetingsAssignmentElementType() {
		return Model_GreetingsAssignment_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_GreetingsGreetingParserRuleCall_0ElementType() {
		return Model_GreetingsGreetingParserRuleCall_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getGreetingElementType() {
		return Greeting_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getGreeting_GroupElementType() {
		return Greeting_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getGreeting_HelloKeyword_0ElementType() {
		return Greeting_HelloKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getGreeting_NameAssignment_1ElementType() {
		return Greeting_NameAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getGreeting_NameIDTerminalRuleCall_1_0ElementType() {
		return Greeting_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getGreeting_ExclamationMarkKeyword_2ElementType() {
		return Greeting_ExclamationMarkKeyword_2_ELEMENT_TYPE;
	}

}
