/*
 * generated by Xtext 2.9.2
 */
package io.chark.idea.lang;

import com.intellij.openapi.fileTypes.FileTypeConsumer;
import com.intellij.openapi.fileTypes.FileTypeFactory;
import org.jetbrains.annotations.NotNull;

public class Kebab_LangFileTypeFactory extends FileTypeFactory {

	@Override
	public void createFileTypes(@NotNull FileTypeConsumer consumer) {
		consumer.consume(Kebab_LangFileType.INSTANCE, AbstractKebab_LangFileType.DEFAULT_EXTENSION);
	}

}
