/*
 * generated by Xtext 2.9.2
 */
package io.chark.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class Kebab_LangLanguage extends AbstractXtextLanguage {

	public static final Kebab_LangLanguage INSTANCE = new Kebab_LangLanguage();

	private Kebab_LangLanguage() {
		super("io.chark.Kebab_Lang");
	}

}
