/*
 * generated by Xtext 2.9.2
 */
package io.chark.idea;

import com.intellij.openapi.extensions.ExtensionFactory;
import io.chark.idea.lang.Kebab_LangLanguage;

public class Kebab_LangExtensionFactory implements ExtensionFactory {
	@Override
	public Object createInstance(String factoryArgument, String implementationClass) {
		Class<?> clazz;
		try {
			clazz = Class.forName(implementationClass);
		} catch (ClassNotFoundException e) {
			throw new IllegalArgumentException("Couldn't load "+implementationClass, e);
		}
		return Kebab_LangLanguage.INSTANCE.<Object> getInstance(clazz);
	}
}
