/*
 * generated by Xtext 2.9.2
 */
package io.chark.idea.lang.pom;

import io.chark.idea.lang.Kebab_LangLanguage;
import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;

public class Kebab_LangPomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {

	public Kebab_LangPomDeclarationSearcher() {
		super(Kebab_LangLanguage.INSTANCE);
	}
}
