/*
 * generated by Xtext 2.9.2
 */
package io.chark.idea.lang.psi.impl;

import com.intellij.openapi.fileTypes.FileType;
import com.intellij.psi.FileViewProvider;
import io.chark.idea.lang.Kebab_LangFileType;
import io.chark.idea.lang.Kebab_LangLanguage;
import org.eclipse.xtext.psi.impl.BaseXtextFile;

public final class Kebab_LangFileImpl extends BaseXtextFile {

	public Kebab_LangFileImpl(FileViewProvider viewProvider) {
		super(viewProvider, Kebab_LangLanguage.INSTANCE);
	}

	@Override
	public FileType getFileType() {
		return Kebab_LangFileType.INSTANCE;
	}
}
