/**
 * generated by Xtext 2.9.2
 */
package io.chark.idea.highlighting;

import io.chark.idea.highlighting.Kebab_LangBaseColorSettingsPage;

@SuppressWarnings("all")
public class Kebab_LangColorSettingsPage extends Kebab_LangBaseColorSettingsPage {
}
