/*
 * generated by Xtext 2.9.2
 */
package io.chark.idea.lang.parser;

import com.google.inject.Inject;
import com.intellij.lang.PsiBuilder;
import io.chark.idea.lang.Kebab_LangElementTypeProvider;
import io.chark.idea.parser.antlr.internal.PsiInternalKebab_LangParser;
import io.chark.services.Kebab_LangGrammarAccess;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import org.antlr.runtime.TokenStream;
import org.eclipse.xtext.idea.parser.AbstractPsiAntlrParser;
import org.eclipse.xtext.idea.parser.AbstractXtextPsiParser;

public class Kebab_LangPsiParser extends AbstractXtextPsiParser {

	private static final Set<String> INITIAL_HIDDEN_TOKENS = new HashSet<String>(Arrays.asList("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT"));

	@Inject 
	private Kebab_LangGrammarAccess grammarAccess;

	@Inject 
	private Kebab_LangElementTypeProvider elementTypeProvider;

	@Override
	protected AbstractPsiAntlrParser createParser(PsiBuilder builder, TokenStream tokenStream) {
		return new PsiInternalKebab_LangParser(builder, tokenStream, elementTypeProvider, grammarAccess);
	}

	@Override
	protected Set<String> getInitialHiddenTokens() {
		return INITIAL_HIDDEN_TOKENS;
	}
}
